# Generated by Django 5.2.11 on 2026-02-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='Certifications and achievements'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='cover_photo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='Education history'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='List of languages with proficiency level'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='response_time_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Typical response time in hours', null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='work_experience',
            field=models.JSONField(blank=True, default=list, help_text='Work experience'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of professional experience', null=True),
        ),
    ]
