# Generated by Django 5.2.11 on 2026-02-17 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_freelancerprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('pay_per_hour', models.DecimalField(decimal_places=2, help_text='Hourly rate in dollars', max_digits=10)),
                ('duration_value', models.PositiveIntegerField(help_text='Duration value')),
                ('duration_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='hours', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Job location', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('skills', models.JSONField(blank=True, default=list, help_text='Required skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='accounts.clientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
