# Generated by Django 5.2.11 on 2026-02-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Whether the profile has minimum required information'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for freelancers to contact you', max_length=20),
        ),
        migrations.AddField(
            model_name='work',
            name='show_contact_info',
            field=models.BooleanField(default=True, help_text='Show contact info to freelancers'),
        ),
    ]
