# Generated by Django 5.2.11 on 2026-02-18 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientprofile_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate quoted by freelancer', max_digits=10)),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated duration in hours')),
                ('cover_letter', models.TextField(help_text='Cover letter/proposal message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether quote email was sent to client')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When email was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='accounts.freelancerprofile')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='accounts.work')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('work', 'freelancer')},
            },
        ),
    ]
