# Generated by Django 5.2.11 on 2026-02-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for clients to contact you', max_length=20),
        ),
    ]
